package cloudwatch

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/osillation/obs/internal/ui"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

type cloudwatchConfig struct {
	Region       string   `yaml:"region"`
	AuthMethod   string   `yaml:"auth_method"`
	Profile      string   `yaml:"profile,omitempty"`
	RoleARN      string   `yaml:"role_arn,omitempty"`
	PollInterval string   `yaml:"poll_interval"`
	LogGroups    []string `yaml:"log_groups"`
	Namespaces   []string `yaml:"namespaces"`
}

func newConnectCmd() *cobra.Command {
	var (
		region       string
		profile      string
		roleARN      string
		logGroups    string
		namespaces   string
		pollInterval string
	)

	cmd := &cobra.Command{
		Use:   "connect",
		Short: "Configure AWS CloudWatch as a metrics/logs data source",
		RunE: func(cmd *cobra.Command, args []string) error {
			client := resolveClientForCW(cmd)
			if client == "" {
				return fmt.Errorf("--client is required")
			}

			if region == "" {
				var err error
				region, err = ui.Prompt("AWS region", "us-east-1")
				if err != nil {
					return err
				}
			}

			authMethod := "profile"
			if roleARN != "" {
				authMethod = "role_arn"
			} else if profile == "" {
				method, err := ui.PromptSelect("Auth method", []string{
					"AWS profile (~/.aws/credentials)",
					"IAM role ARN (assume-role)",
					"Environment variables (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY)",
				})
				if err != nil {
					return err
				}
				switch {
				case strings.HasPrefix(method, "AWS profile"):
					authMethod = "profile"
					profile, _ = ui.Prompt("AWS profile name", "default")
				case strings.HasPrefix(method, "IAM role"):
					authMethod = "role_arn"
					roleARN, _ = ui.Prompt("IAM role ARN", "")
				default:
					authMethod = "env"
				}
			}

			if pollInterval == "" {
				pollInterval, _ = ui.Prompt("Poll interval", "60s")
			}

			var lgList, nsList []string
			if logGroups != "" {
				lgList = splitTrim(logGroups)
			} else {
				ui.Info("Enter log groups to import (comma-separated, or press enter to skip)")
				input, _ := ui.Prompt("Log groups", "")
				if input != "" {
					lgList = splitTrim(input)
				}
			}
			if namespaces != "" {
				nsList = splitTrim(namespaces)
			} else {
				input, _ := ui.Prompt("Namespaces", "AWS/ECS,AWS/RDS,AWS/ApplicationELB")
				nsList = splitTrim(input)
			}

			cfg := cloudwatchConfig{
				Region:       region,
				AuthMethod:   authMethod,
				Profile:      profile,
				RoleARN:      roleARN,
				PollInterval: pollInterval,
				LogGroups:    lgList,
				Namespaces:   nsList,
			}

			p := resolvePlatformForCW(cmd)
			clientDir := p.ClientDir(client)
			if err := os.MkdirAll(clientDir, 0755); err != nil {
				return fmt.Errorf("creating client dir: %w", err)
			}
			outPath := filepath.Join(clientDir, "cloudwatch.yml")

			data, err := yaml.Marshal(cfg)
			if err != nil {
				return err
			}

			if err := os.WriteFile(outPath, data, 0600); err != nil {
				return fmt.Errorf("writing cloudwatch.yml: %w", err)
			}

			if err := writeReceiverSnippet(p.PlatformDir(), cfg); err != nil {
				return err
			}

			ui.Success("Written: " + outPath)
			ui.Success("OTel receiver config updated")
			fmt.Println()
			fmt.Printf("  Logs:    %s\n", strings.Join(lgList, ", "))
			fmt.Printf("  Metrics: %s\n", strings.Join(nsList, ", "))
			fmt.Printf("  Region:  %s\n", region)
			fmt.Printf("  Polling: every %s\n", pollInterval)
			fmt.Println()
			ui.Dim("Restart the collector to apply: obs dashboard stop && obs dashboard start")
			return nil
		},
	}

	cmd.Flags().StringVar(&region, "region", "", "AWS region (e.g. us-east-1)")
	cmd.Flags().StringVar(&profile, "profile", "", "AWS profile name")
	cmd.Flags().StringVar(&roleARN, "role-arn", "", "IAM role ARN for assume-role auth")
	cmd.Flags().StringVar(&logGroups, "log-groups", "", "comma-separated CloudWatch log groups")
	cmd.Flags().StringVar(&namespaces, "namespaces", "", "comma-separated metric namespaces")
	cmd.Flags().StringVar(&pollInterval, "poll-interval", "60s", "how often to poll CloudWatch")
	return cmd
}

func writeReceiverSnippet(platformDir string, cfg cloudwatchConfig) error {
	snippet := buildOTelSnippet(cfg)
	outDir := filepath.Join(platformDir, "config", "otel", "receivers")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("creating receiver dir: %w", err)
	}
	outPath := filepath.Join(outDir, "cloudwatch.yaml")
	return os.WriteFile(outPath, []byte(snippet), 0644)
}

func buildOTelSnippet(cfg cloudwatchConfig) string {
	var sb strings.Builder

	sb.WriteString("# Generated by obs cloudwatch connect — do not edit manually\n")
	sb.WriteString("receivers:\n")

	if len(cfg.LogGroups) > 0 {
		sb.WriteString("  awscloudwatchreceiver:\n")
		sb.WriteString(fmt.Sprintf("    region: %s\n", cfg.Region))
		sb.WriteString("    logs:\n")
		sb.WriteString(fmt.Sprintf("      poll_interval: %s\n", cfg.PollInterval))
		sb.WriteString("      groups:\n")
		sb.WriteString("        named:\n")
		for _, lg := range cfg.LogGroups {
			sb.WriteString(fmt.Sprintf("          %s:\n", lg))
			sb.WriteString("            prefixes: [\"\"]\n")
		}
	}

	if len(cfg.Namespaces) > 0 {
		sb.WriteString("  awscloudwatchmetrics:\n")
		sb.WriteString(fmt.Sprintf("    region: %s\n", cfg.Region))
		sb.WriteString(fmt.Sprintf("    poll_interval: %s\n", cfg.PollInterval))
		sb.WriteString("    metrics:\n")
		for _, ns := range cfg.Namespaces {
			sb.WriteString(fmt.Sprintf("      - namespace: %s\n", ns))
			sb.WriteString("        dimensions: []\n")
		}
	}

	sb.WriteString("\nservice:\n")
	sb.WriteString("  pipelines:\n")
	if len(cfg.LogGroups) > 0 {
		sb.WriteString("    logs/cloudwatch:\n")
		sb.WriteString("      receivers: [awscloudwatchreceiver]\n")
		sb.WriteString("      processors: [batch, memory_limiter]\n")
		sb.WriteString("      exporters: [otlp/signoz]\n")
	}
	if len(cfg.Namespaces) > 0 {
		sb.WriteString("    metrics/cloudwatch:\n")
		sb.WriteString("      receivers: [awscloudwatchmetrics]\n")
		sb.WriteString("      processors: [batch, memory_limiter]\n")
		sb.WriteString("      exporters: [otlp/signoz]\n")
	}

	return sb.String()
}

func splitTrim(s string) []string {
	parts := strings.Split(s, ",")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	return parts
}
